name: GitHub
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'debug'
      tags:
        description: 'Testing CodeGuru Security.'
        
permissions:
  id-token: write
  # for writing security events.
  security-events: write
  # only required for workflows in private repositories
  actions: read
  contents: read

jobs:
  login:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Respository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          
      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::579795239548:role/CodeGuruSecurityGitHubAccessRole
          aws-region: us-west-2
          role-session-name: GitHubActionScript

      - name: ECR Login
        id: login-to-ecr
        uses: aws-actions/amazon-ecr-login@v1
        with:
          registries: '324798398040'
          aws-region: us-west-2
      - name: Docker Pull
        run: |
          docker pull 324798398040.dkr.ecr.us-west-2.amazonaws.com/codegurusecurity-actions
          docker image tag 324798398040.dkr.ecr.us-west-2.amazonaws.com/codegurusecurity-actions codeguru:latest
      - name: Run Action Script
        uses: docker://codeguru:latest
        with:
          args: "--source_path . --aws_region us-east-1 --output_file codeguru-security-results"
      - name: print findings.
        run: |
          ls -l
          cat codeguru-security-results.sarif.json
      - name: Upload review result
        if: ${{ github.event_name != 'push' }}
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: codeguru-security-results.sarif.json
